### ISSUE TITLE
Pecube-D no CMakeLists.txt to build with

### ISSUE THREAD

**Issue by acchapm1** [toddehlers/ESDSimulator#1]
I am attempting to build this version of Pecube-D on our cluster for a researcher and ran into an issue that I am not able to get around.   Would it be possible to use the CMakeList.txt from the main Pecube github?   Thanks

**Comment by willi-kappler** [comment]
In order to compile it you need the scons build tool. Once it is installed you go to the specific folder:

cd src/Pecube_D

And then type:

scons --use-mpi

to compile it.

**Comment by acchapm1** [comment]
what version of scons and mpi are you using?   I have not had any luck with the combinations of compilers and mpi versions I have currently.   

These are the ones ive tried.   All of these are built with spack on a compute cluster. 
1) scons-4.3.0-gcc-11.2.0   2) mpich-4.0.2-gcc-11.2.0

 1) scons-4.3.0-gcc-11.2.0   2) openmpi-4.1.5-gcc-11.2.0

Thanks

**Comment by willi-kappler** [comment]
scons: v3.1.2
gcc: 9.4.0
openmpi: 4.0.3

What was the exact error message ?
There is also a singularity container, Todd Ehlers provided more details.

**Comment by acchapm1** [comment]
I will try with those versions of tools.  

The error I received is below. 

`[software@c001:Pecube_D]# module list
Currently Loaded Modulefiles:
 1) scons-4.3.0-gcc-11.2.0   2) mpich-4.0.2-gcc-11.2.0
[software@c001:Pecube_D]# scons --use-mpi
scons: Reading SConscript files ...
g++ found, setting options...
CCFLAGS: -Wall -Wextra -Werror -Wno-error=maybe-uninitialized -O3 -g3
using the mpi fortran wrapper, setting options...
FORTRAN: mpifort
LINK: mpifort, LINKFLAGS: -fopenmp -O3 -g3, LIBS: stdc++
F90FLAGS: -Werror -Wall -Wunderflow -Wno-error=maybe-uninitialized -ffree-line-length-none -fopenmp -O3 -g3
System is Linux, running updateVersion...
scons: done reading SConscript files.
scons: Building targets ...
mpifort -o monte_carlo.o -c -Werror -Wall -Wunderflow -Wno-error=maybe-uninitialized -ffree-line-length-none -fopenmp -O3 -g3 -I. monte_carlo.f90
mpifort -o version.o -c -Werror -Wall -Wunderflow -Wno-error=maybe-uninitialized -ffree-line-length-none -fopenmp -O3 -g3 -I. version.f90
monte_carlo.f90:260:34:

  236 |                             call MPI_SEND(number_of_good_fits(j), 1, MPI_INTEGER8, mc_mpi_status(MPI_SOURCE), 0, &
      |                                          2
......
  260 |                     call MPI_SEND(has_good_fit, 1, MPI_LOGICAL, 0, 0, MPI_COMM_WORLD, mc_mpi_error)
      |                                  1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(8)). [-Werror]
monte_carlo.f90:266:34:

  226 |                         call MPI_RECV(other_has_good_fit, 1, MPI_LOGICAL, MPI_ANY_SOURCE,&
      |                                      2
......
  266 |                     call MPI_RECV(number_of_good_fits(j), 1, MPI_INTEGER8, MPI_ANY_SOURCE, &
      |                                  1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(8)/LOGICAL(4)). [-Werror]
f951: all warnings being treated as errors
scons: *** [monte_carlo.o] Error 1
scons: building terminated because of errors.`

**Comment by acchapm1** [comment]
Found the definition files for singularity and am building the sif images currently.  Thank you!

**Comment by toddehlers** [comment]
Hi Alan,I think the current version of the Pecube.in file on GitHub (or via the Zenodo DOI I sent you) says near the top of the document what versions we use to compile it. Let me know if that doesn’t resolve it.TESent from my iPad*************************Prof. Todd EhlersDepartment of GeosciencesUniversity of Tübingen, GermanyOn 12 Apr 2023, at 19:39, Alan Chapman ***@***.***> wrote:﻿
what version of scons and mpi are you using?   I have not had any luck with the combinations of compilers and mpi versions I have currently.
These are the ones ive tried.   All of these are built with spack on a compute cluster.


scons-4.3.0-gcc-11.2.0   2) mpich-4.0.2-gcc-11.2.0


scons-4.3.0-gcc-11.2.0   2) openmpi-4.1.5-gcc-11.2.0


Thanks

**Comment by willi-kappler** [comment]
Here is some more information if needed:

[https://zenodo.org/record/7785668#.ZCWhGC8Rpxc](https://zenodo.org/record/7785668#.ZCWhGC8Rpxc)

**Comment by acchapm1** [comment]
Thank you for all the help!   I was able to get the singularity container built and am waiting for the researcher (Stephanie Sparks) I'm working with to test it out.

**Comment by willi-kappler** [comment]
You're welcome! I'll close this issue now, feel free to open a new one if you have more questions / problems.
