### ISSUE TITLE
Containerized Pecube-D and MPI

### ISSUE THREAD

**Issue by acchapm1** [toddehlers/ESDSimulator#2]
I have built he containers for Pecube-D for the researcher im working with, it is working well in single process mode.  When she tries to do the Monty Carlo options in the Pecube.in file it errors out as the container is not started with mpi enabled.   What commands are you using to start the container to utilize mpi?   We use Slurm as our scheduler and it replaces mpirun with srun, if I can see how others run the container with mpirun I can reverse engineer it to work with srun.

**Comment by toddehlers** [comment]
Hi Willi,
Can you answer this - I’m not as familiar with the container and running the MPI version.
TE


**** New Contact Info ****
Todd Ehlers
Professor (MAE <https://www.ae-info.org/>)
http://www.esdynamics.net <http://www.esdynamics.net/> 
EarthShapeSPP http://www.earthshape.net  <http://www.esdynamics.net/>
****
University of Glasgow
School of Geographical and Earth Sciences
East Quadrangle
G12 8QQ Glasgow, Scotland, UK

Office Phone: TBA
Mobile: +44 7407
****

**Comment by willi-kappler** [comment]
We use Torque / Moab and compile it directly on the cluster. We've never run the container with MPI, sorry!
Maybe the Singularity / Apptainer documentation can help you further ?

**Comment by acchapm1** [comment]
I will see what I can get to work.  If i find a solution, ill share it here.

**Comment by acchapm1** [comment]
We have gotten the Pecube-D apptainer working on a Slurm managed cluster with the following sbatch script.  

```
#!/bin/bash
​
#SBATCH -N 4            # number of nodes
##SBATCH -c 20            # number of cores
#SBATCH -t 0-01:00:00   # time in d-hh:mm:ss
#SBATCH -p general      # partition
#SBATCH -q public       # QOS
#SBATCH -o slurm.%j.out # file to save job's STDOUT (%j = JobId)
#SBATCH -e slurm.%j.err # file to save job's STDERR (%j = JobId)
#SBATCH --mail-type=ALL # Send an e-mail when a job starts, stops, or fails
#SBATCH --mail-user=%u@asu.edu
​
srun --export=ALL --nodes=4 apptainer exec /packages/apps/simg/pecube-d.sif /bin/pecube /KG01Test/Pecube.in
```

This is specific to our cluster but the principals are straight forward.   the key to get it working was to add --export=ALL to the srun command.

**Comment by willi-kappler** [comment]
Thanks for trying it out, that's very useful!
Glad to hear that it works now, I'll close this issue now.
