### ISSUE TITLE
Possible 2-D example model issue

### ISSUE THREAD

**Issue by chronictectonic** [toddehlers/ESDSimulator#3]
Hello,

I'm trying to get started using 2-D and I'm beginning with the example given here (2D_move_mcquarrie_ehlers_2015). The log file indicates that it reads up to time step 3 and then fails for an unknown reason.

I get an error from the slurm scheduler that says:

```
At line 250 of file create_pecube_in.f90
Fortran runtime error: Bad integer for item 5 in list input

```
I looked into the source code and it appears to be "temperature_hold_period" and I'm not sure to which input this refers to (I was thinking something from 12a). However, I used the Pecube.in file provided here so I'm not sure why there is any error.

Any assistance would be greatly appreciated.

Thank you,
Stephanie

**Comment by toddehlers** [comment]
Hi Stephanie,
We don’t really provide support for the GitHub repository.  But based on your error message it sounds like .in file for doing intrusions was mixed up, or a line changed in the mcquarrie ehlers example you are using.  You don’t need to do a hold time.  It could also be there is flag set earlier for doing intrusions and it’s expecting a value on the line where it gave the error message.

I suggest starting with a simple simulation of a 3D block with flat topography and running it.  Then add complexity in from there.

If you want a working example, then the Pecube-D entry in Zenodo.org has a F&TB example from a paper by Paul Eizenhoefer.

I hope this helps.
Best wishes,
Todd

**** New Contact Info ****
Todd Ehlers
Professor (MAE<https://www.ae-info.org/>)
https://www.gla.ac.uk/schools/ges/staff/toddehlers/
****
University of Glasgow
School of Geographical and Earth Sciences, East Quadrangle
Glasgow
G12 8QQ
Scotland, UK

Office location: Room 317 East Quad
Office Phone: +44 (0) 141 330 4224<tel:+441413304224>
Mobile: +44 (0) 7407 068805<tel:+447407068805>

EarthShape SPP 1803 http://www.earthshape.net<https://esdynamics.geo.uni-tuebingen.de/earthshape/index.php?id=129>
****



From: Stephanie Sparks ***@***.***>
Date: Thursday, 6. July 2023 at 17:40
To: toddehlers/ESDSimulator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [toddehlers/ESDSimulator] Possible 2-D example model issue (Issue #3)

Hello,

I'm trying to get started using 2-D and I'm beginning with the example given here (2D_move_mcquarrie_ehlers_2015). The log file indicates that it reads up to time step 3 and then fails for an unknown reason.

I get an error from the slurm scheduler that says:

At line 250 of file create_pecube_in.f90

Fortran runtime error: Bad integer for item 5 in list input



I looked into the source code and it appears to be "temperature_hold_period" and I'm not sure to which input this refers to (I was thinking something from 12a). However, I used the Pecube.in file provided here so I'm not sure why there is any error.

Any assistance would be greatly appreciated.

Thank you,
Stephanie

**Comment by chronictectonic** [comment]
Thanks for getting back to me. 

I will take your suggestions and work from a simple block model and build complexity.

I'll also check the Zenodo example.

Thanks very much,
Stephanie

**Comment by toddehlers** [comment]
Hi Stephanie,
I just realized that you are the student working with Kip using Pecube-D.  I had forgotten your name and your email didn’t allude to that.  Anyway – my apologies!
Have you been able to make some progress?

Best wishes,
Todd

**** New Contact Info ****
Todd Ehlers
Professor (MAE<https://www.ae-info.org/>)
https://www.gla.ac.uk/schools/ges/staff/toddehlers/
****
University of Glasgow
School of Geographical and Earth Sciences, East Quadrangle
Glasgow
G12 8QQ
Scotland, UK

Office location: Room 317 East Quad
Office Phone: +44 (0) 141 330 4224<tel:+441413304224>
Mobile: +44 (0) 7407 068805<tel:+447407068805>

EarthShape SPP 1803 http://www.earthshape.net<https://esdynamics.geo.uni-tuebingen.de/earthshape/index.php?id=129>
****



From: Stephanie Sparks ***@***.***>
Date: Friday, 7. July 2023 at 17:29
To: toddehlers/ESDSimulator ***@***.***>
Cc: Todd A Ehlers ***@***.***>, Comment ***@***.***>
Subject: Re: [toddehlers/ESDSimulator] Possible 2-D example model issue (Issue #3)

Thanks for getting back to me.

I will take your suggestions and work from a simple block model and build complexity.

I'll also check the Zenodo example.

Thanks very much,
Stephanie

**Comment by chronictectonic** [comment]
Hi Todd,

Yes, it is me.

1-D has gone really well and I'm making good progress on that front, but my next goal is to successfully build a 2-D model. I'm working on this still as I haven't been able to get results using monte carlo mode just yet, but I think I'm close.

I'm also working on creating the simple block model you suggested, should have that running by tomorrow.

Thanks for checking in,
Stephanie

**Comment by chronictectonic** [comment]
I guess I should have waited before sending the last message because I did just get the 2-D working. Now I need to add in the complexities.
